"use client";

interface DownloadPDFProps {
  title: string;
  content: string;
  author: string;
}

export default function DownloadPDF({ title, content, author }: DownloadPDFProps) {
  const handleDownload = () => {
    const date = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>${title}</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              max-width: 800px;
              margin: 40px auto;
              padding: 0 20px;
              color: #333;
              line-height: 1.6;
            }
            .header {
              border-bottom: 2px solid #6C63FF;
              padding-bottom: 16px;
              margin-bottom: 24px;
            }
            .logo {
              color: #6C63FF;
              font-size: 14px;
              font-weight: bold;
              margin-bottom: 8px;
            }
            h1 {
              font-size: 24px;
              color: #1a1a2e;
              margin: 0 0 8px 0;
            }
            .meta {
              font-size: 12px;
              color: #888;
            }
            .content {
              white-space: pre-wrap;
              font-size: 14px;
              line-height: 1.8;
            }
            .footer {
              margin-top: 40px;
              padding-top: 16px;
              border-top: 1px solid #eee;
              font-size: 12px;
              color: #aaa;
              text-align: center;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="logo">📚 Group Helper</div>
            <h1>${title}</h1>
            <div class="meta">Written by ${author} · ${date}</div>
          </div>
          <div class="content">${content}</div>
          <div class="footer">Generated by Group Helper · grouphelper.app</div>
        </body>
      </html>
    `;

    const blob = new Blob([htmlContent], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${title.replace(/\s+/g, "-").toLowerCase()}.html`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={handleDownload}
      className="btn btn-xs gap-1"
      style={{ background: "#2a2a4a", color: "white", border: "none" }}
    >
      <span>📄</span>
      Download
    </button>
  );
}